# Generated by Django 5.1.4 on 2024-12-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_sample',
            new_name='tbl_admin',
        ),
    ]
