# Generated by Django 5.1.4 on 2024-12-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=30)),
                ('hospital_email', models.CharField(max_length=30)),
                ('hospital_contact', models.CharField(max_length=30)),
                ('hospital_district', models.CharField(max_length=30)),
                ('hospital_address', models.CharField(max_length=50)),
                ('hospital_photo', models.FileField(upload_to='Assets/Files/User/Photo/')),
                ('hospital_proof', models.FileField(upload_to='Assets/Files/User/Photo/')),
                ('hospital_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
