# Generated by Django 5.1.4 on 2024-12-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_authority',
        ),
    ]
