# Generated by Django 5.1.4 on 2024-12-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=30)),
                ('authority_email', models.CharField(max_length=30)),
                ('authority_contact', models.CharField(max_length=30)),
                ('authority_district', models.CharField(max_length=30)),
                ('authority_address', models.CharField(max_length=50)),
                ('authority_photo', models.FileField(upload_to='Assets/Files/User/Photo/')),
                ('authority_proof', models.FileField(upload_to='Assets/Files/User/Photo/')),
                ('authority_password', models.CharField(max_length=30)),
                ('authority_status', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
