# Generated by Django 5.1.4 on 2024-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_authority',
            name='authority_status',
            field=models.IntegerField(default=0),
        ),
    ]
