# Generated by Django 5.1.4 on 2024-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_authority_authority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_hospital',
            name='authority_status',
            field=models.IntegerField(default=0),
        ),
    ]
