# Generated by Django 5.1.4 on 2024-12-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_hospital_authority_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_hospital',
            old_name='authority_status',
            new_name='hospital_status',
        ),
    ]
