# Generated by Django 5.1.4 on 2024-12-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/Files/User/Photo')),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
