# Generated by Django 5.1.4 on 2024-12-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0002_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(upload_to='Assets/Files/User/Photo/')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requestbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestbody_status', models.CharField(max_length=30)),
                ('authority_id', models.CharField(max_length=30)),
                ('hospital_id', models.CharField(max_length=30)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
